###

GET http://localhost:9998/api/cards/1 HTTP/1.1
Accept: application/json
X-CustomHeader: custom header


###
GET http://localhost:9999/banners.save?id=0 HTTP/1.1

###
GET http://localhost:9999/banners.getAll HTTP/1.1


###
GET http://localhost:9999/banners.getById HTTP/1.1

###
GET http://localhost:9999/banners.removeById HTTP/1.1

